/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.snimmagadda1;

public class App {
    public String getGreeting() {
        return "_template Hello World!";
    }

    public static void main(String[] args) {
        // final ApplicationContext applicationContext = new ApplicationContext(Step3App.class);
        // final CompanyService companyServiceProxy = applicationContext.getBean(CompanyService.class);

        // companyServiceProxy.createCompany(new Company());
    }
}
